source "http://rubygems.org"
gemspec

gem 'ecm_core', path: '../ecm_core'
gem 'administrador', path: '~/rails/gems/administrador'
gem 'rao-resource_controller', path: '~/rails/gems/rao/rao-resource_controller'
# gem 'rao-resources_controller', path: '~/rails/gems/rao/rao-resources_controller'